### ISSUE TITLE
Make a conda package

### ISSUE THREAD

**Issue by johnlees** [tmaklin/cpprate#8]
Would be handy on conda-forge, I'll do this now

**Comment by johnlees** [comment]
https://github.com/conda-forge/staged-recipes/pull/24167

**Comment by tmaklin** [comment]
thanks, I'm not sure if the build system is conda compatible so let me know if there are any issues.

**Comment by johnlees** [comment]
Seems to be working! Hopefully it will get reviewed and merged soon. Then it should auto-update when you make new releases

**Comment by tmaklin** [comment]
Great! Can you put in a pull request with installation instructions added to the readme once it's merged.

**Comment by tmaklin** [comment]
They seem to have requested some changes to bundling dependencies that will probably require a few changes in the source code - I can handle them if you give me push access to your recipe repository.

**Comment by tmaklin** [comment]
hey, this seems like it's been merged into conda-forge! Do you want credit for the recipe? If so make a pull req adding something to the readme; otherwise I'll do it at some point.

**Comment by johnlees** [comment]
No worries, happy just to contribute 🙂
